# Generated by Django 3.1.3 on 2020-11-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(help_text='Zeitpunkt des Termins')),
                ('comment', models.CharField(help_text='Freies Kommentar. Gib hier alles ein, was zu diesem Termin wichtig ist.', max_length=256)),
            ],
        ),
    ]
