# Generated by Django 3.1.3 on 2020-11-10 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Scheduling', 'verbose_name_plural': 'Scheduling'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 11, 10, 17, 6, 42, 468991), help_text='Tag des Termins', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 10, 17, 6, 42, 468990), help_text='Ende des Termins', verbose_name='Ende'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 10, 17, 6, 42, 468990), help_text='Beginn des Termins', verbose_name='Beginn'),
        ),
    ]
