# Generated by Django 3.1.3 on 2020-11-10 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termin_app', '0002_auto_20201110_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Termin', 'verbose_name_plural': 'Termine'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 11, 10, 17, 7, 58, 622031), help_text='Tag des Termins', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 10, 17, 7, 58, 622030), help_text='Ende des Termins', verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 10, 17, 7, 58, 622030), help_text='Beginn des Termins', verbose_name='Beginn'),
        ),
    ]
