# Generated by Django 3.1.3 on 2020-11-10 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termin_app', '0003_auto_20201110_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.CharField(help_text='Freies Kommentar. Gib hier alles ein, was zu diesem Termin wichtig ist.', max_length=256, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 11, 10, 17, 9, 32, 538765), help_text='Tag des Termins', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 10, 17, 9, 32, 538765), help_text='Ende des Termins', verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 10, 17, 9, 32, 538765), help_text='Beginn des Termins', verbose_name='Beginn'),
        ),
    ]
